- name: tasks_for_isu
  hosts: isu1
  gather_facts: false
  user: ubuntu
  become: true
  max_fail_percentage: 0
  vars_files: ../var.yml
  tasks: "{{ item }}"
  loop: "{{ var['isu1_tasks_for_isu'] }}"  
    #- import_tasks : ../tasks/common/common.yml
    #- import_tasks : ../tasks/monitoring/fluent-bit.yml
    #- import_tasks : ../tasks/monitoring/node_exporter.yml
    #- import_tasks : ../tasks/tasks_for_isu/alp.yml
    #- import_tasks : ../tasks/tasks_for_isu/graphviz.yml
    #- import_tasks : ../tasks/tasks_for_isu/mysql.yml
    #- import_tasks : ../tasks/tasks_for_isu/netdata.yml
    #- import_tasks : ../tasks/tasks_for_isu/nginx.yml
    #- import_tasks : ../tasks/tasks_for_isu/parameter.yml
    #- import_tasks : ../tasks/tasks_for_isu/percona.yml
    #- import_tasks : ../tasks/tasks_for_isu/redis.yml

- name: isu
  hosts: isu1
  gather_facts: false
  user: ubuntu
  become: true
  max_fail_percentage: 0
  vars_files: ../var.yml
  tasks:
    #- import_tasks : ../tasks/isu/isu_pre.yml
    #- import_tasks : ../tasks/isu/isu1.yml
    #- import_tasks : ../tasks/isu/isu_add.yml