- name: tasks_for_isu
  hosts: isu2
  gather_facts: no
  user: ubuntu
  become: yes
  max_fail_percentage: 0
  tasks:
    - import_tasks : ../tasks/common/common.yml
    #- import_tasks : ../tasks/monitoring/fluent-bit.yml
    #- import_tasks : ../tasks/monitoring/node_exporter.yml
    #- import_tasks : ../tasks/tasks_for_isu/alp.yml
    - import_tasks : ../tasks/tasks_for_isu/graphviz.yml
    #- import_tasks : ../tasks/tasks_for_isu/mysql.yml
    - import_tasks : ../tasks/tasks_for_isu/netdata.yml
    #- import_tasks : ../tasks/tasks_for_isu/nginx.yml
    - import_tasks : ../tasks/tasks_for_isu/parameter.yml
    #- import_tasks : ../tasks/tasks_for_isu/percona.yml
    #- import_tasks : ../tasks/tasks_for_isu/redis.yml

- name: isu
  hosts: isu2
  gather_facts: no
  user: ubuntu
  become: yes
  max_fail_percentage: 0
  tasks:
    - import_tasks : ../tasks/isu/isu2.yml