- name: isu-ruby is disabled
  systemd:
    name: isu-ruby
    state: stopped
    enabled: false

- name: isu-go is running
  systemd:
    name: isu-go
    state: started
    enabled: true

- name: Git checkout
  git:
    repo: https://github.com/megutamago/my-ansible-isu-templete.git
    dest: /home/isucon/my-ansible-isu-templete

- name: Copy
  copy:
    src: /home/isucon/private_isu/webapp
    dest: /home/isucon/private_isu/.bk
    remote_src: yes
  ignore_errors: yes

- name: remove
  file: 
    path: /home/isucon/private_isu/webapp
    state: absent

- name: Copy
  copy:
    src: /home/isucon/my-ansible-isu-templete/webapp
    dest: /home/isucon/private_isu/
    owner: isucon
    group: isucon
    remote_src: yes
  ignore_errors: yes

- name: remove
  file: 
    path: /home/isucon/my-ansible-isu-templete
    state: absent

### Execute as login shell
- name: setup
  shell: sudo -u isucon bash -lc "sh setup.sh"
  args:
    chdir: /home/isucon/private_isu/webapp/golang/

- name: isu-go is restarted
  systemd:
    name: isu-go
    state: restarted

- name: remove
  file: 
    path: /var/log/nginx/access.log
    state: absent

- name: nginx is restarted
  systemd:
    name: nginx
    state: restarted

- name: remove
  file: 
    path: /var/log/mysql/mysql-slow.sql
    state: absent

- name: chmod
  file: 
    path: /home/isucon/private_isu/webapp/sql/init.sh
    mode: '0755'
  ignore_errors: yes

#- name: shell
#  shell: sh /home/isucon/private_isu/webapp/sql/init.sh

- name: mysql is restarted
  systemd:
    name: mysql
    state: restarted

- name: redis is restarted
  systemd:
    name: redis-server
    state: restarted
  ignore_errors: yes