name: 'isu'
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Ansible:
    name: "Ansible1 Job"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/isu.yml
          directory: ./ansible
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [isu1]
            ${{ vars.HOST1 }}
            [isu2]
            ${{ vars.HOST2 }}
            [isu3]
            ${{ vars.HOST3 }}
          options: |
            --inventory .hosts