name: 'isu3'
on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:
jobs:
  Ansible3:
    name: "Ansible3 Job"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/isu3.yml
          directory: ./ansible
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [isu3]
            ${{ vars.HOST3 }}
          options: |
            --inventory .hosts
  Deploy3:
    name: "Deploy3 Job"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Exe
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.HOST3 }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          #script: |
          #  cd /home/isucon/private_isu/webapp/golang/
          #  bash -lc "go get github.com/redis/go-redis/v8"
          #  sudo systemctl restart isu-go